name: PHP Composer

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          load-mode: strict

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql username: ${{ env.MYSQL_USERNAME }}
          mysql database: ${{ env.MYSQL_DATABASE }}
          mysql root password: ${{ env.MYSQL_PASSWORD }}

      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 15-alpine
          app_user: ${{ env.POSTGRESQL_USERNAME }}
          app_user_password: ${{ env.POSTGRESQL_PASSWORD }}
          app_db: ${{ env.POSTGRESQL_DATABASE }}

      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Waiting for MySQL
        run: |
          while ! mysqladmin ping --host=${{ env.MYSQL_HOST }} --password=${{ env.MYSQL_PASSWORD }} --silent; do
            sleep 1
          done

      - name: PHPUnit
        run: ./vendor/bin/phpunit
